### ISSUE TITLE
App crashes when a saved Rdata file is loaded

### ISSUE THREAD

**Issue by arumds** [jminnier/STARTapp#12]
We noticed that the Rdata file produced from the current version is different from the previous version. However, when the saved Rdata file generated from the current version is uploaded to the same current version crashes the application.

**Comment by jminnier** [comment]
Thank you for reporting this, I'll try to fix it asap!

**Comment by florianduclot** [comment]
@jminnier , @arumds ,

I also encountered the same issue, with the following in the logs (local instance):
```
Warning: Error in <reactive:inputDataReactive>: object 'data_results_table' not found
  113: <reactive:inputDataReactive> [server-inputdata.R#79]
   97: inputDataReactive
   96: <reactive:output$fileUploaded> [server-inputdata.R#114]
   80: output$fileUploaded
    1: runApp
Warning: Error in <reactive:inputDataReactive>: object 'data_results_table' not found
  61: <Anonymous>
```

After a quick look, it seems that the `data_results_table` is actually part of the `start_list` object.
I'm not that familiar with how the Save RData works with shiny, but correcting this when uploading the file seems to be fixing the issue.
I'm going to submit a PR in case it helps.

**Comment by jminnier** [comment]
Oh thank you very much @florianduclot ! These COVID days have gotten away from me and I didn't have a chance to look into this closely enough, but this is very helpful. I'll check out the PR and incorporate it in the next day or two!

**Comment by jminnier** [comment]
Hi @florianduclot and @arumds, thanks for your patience, I accepted @florianduclot's fix (thank you!!) and this seems to be working now. Sorry for the delay! Also a couple other updates were made (just getting rid of deprecated functions) and I might make a few more soon, so please let me know if you have any issues with the new version.
