### ISSUE TITLE
Error: non-character argument, Volcano Plot

### ISSUE THREAD

**Issue by aymanm** [jminnier/STARTapp#3]
I tried following the installation instructions. The app works and I can upload csv data, but when I goto Analysis Plots, I get "Error: non-character argument". I even tried the example csv data, with the same result. Please advise.

This is the stack trace in the console:

Warning: Error in strsplit: non-character argument
Stack trace (innermost first):
    87: strsplit
    86: do.call
    85: rna_volcanoplot [fun-analysisres.R#97]
    84: eval [server-analysisres.R#76]
    83: eval
    82: withProgress
    81: "plotly"::"ggplotly" [server-analysisres.R#67]
    80: func
    79: origRenderFunc
    78: output$volcanoplot
     3: runApp
     2: runUrl
     1: shiny::runGitHub

**Comment by aymanm** [comment]
the following changes to "fun-analysisres.R" fixed it. Maybe required for new versions of plotly/ggplot. See diff in this Url:

http://www.mergely.com/n7cQN7IU/

**Comment by jminnier** [comment]
Thank you, @aymanm, you're definitely right, at some point a new version of plotly broke this part. Thanks for letting me know! I'll change it, or feel free to submit a pull request if you like. Great catch! It's high time I double check the code works with the newer version of packages.

**Comment by aymanm** [comment]
You're welcome @jminnier , its a great application.
please see pull request https://github.com/jminnier/STARTapp/pull/4
